### ISSUE TITLE
SHA-512 - bad hash calculated

### ISSUE THREAD

**Issue by jaclas** [decfpc/DelphiEncryptionCompendium#1]
I try use THash_SHA512 and result is is different than e.g. here:

http://www.convertstring.com/pl/Hash/SHA512

The THashSHA2 class is available from Delphi Seattle, which also has a different hash than the DEC class.

**Comment by decfpc** [comment]
THash_SHA512 is producing correct results. There was probably an issue with how you called the Calc* method.

If you're still facing this issue, please comment with the code you're using the calculate the hash.
