### ISSUE TITLE
Compatability with older library version

### ISSUE THREAD

**Issue by JJDGitHub** [decfpc/DelphiEncryptionCompendium#2]
I am attempting to recreate a library written in long ago with the then current version of DEC.  This library using Blowfish cipher to encrypt a string using a hexadecimal key value.  

The issue is when I duplicate the functionality using the current library and the previous key value I do not get the same hexadecimal result.  Is the current library compatible with the old?

**Comment by mdsystems** [comment]
Is there any chance that you are using Unicode strings now and back then were using ANSI strings? If so, you could try typecasting the strings to AnsiString and see if you observe the same problem.
